#------Pages
home:
  path: /
  controller: App\Controller\SiteController::index

new:
  path: /new
  controller: App\Controller\SiteController::newTrack

#----- Links for Track
upload_file:
  path: /tracks/upload
  controller: App\Controller\TrackController::uploadFile

download_file:
  path: /tracks/download/{fileID}
  controller: App\Controller\TrackController::downloadFile

update_file:
  path: /tracks/update/{fileID}
  controller: App\Controller\TrackController::updateFileInfo

delete_file:
  path: /tracks/delete/{fileID}
  controller: App\Controller\TrackController::deleteFile

tracks:
  path: /tracks
  controller: App\Controller\TrackController::getTracksList

track_id:
  path: /tracks/{ID}
  controller: App\Controller\TrackController::getTrackByID

# ----- Links for Tag
tags:
  path: /tags
  controller: App\Controller\TagController::getTagsList

add_new_tag:
  path: /tags/add
  controller: App\Controller\TagController::addNewTrack

delete_tag:
  path: /tags/delete/{tagID}
  controller: App\Controller\TagController::deleteTag

update_tag:
  path: /tags/update/{tagID}
  controller: App\Controller\TagController::updateTag

categories:
  path: /tags/categories
  controller: App\Controller\TagController::getCategories
